# Generated by Django 5.2 on 2025-04-08 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], max_length=50)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_feedback_count', models.IntegerField()),
                ('pending_feedback_count', models.IntegerField()),
                ('overall_satisfaction_score', models.FloatField()),
                ('admin', models.ForeignKey(limit_choices_to={'role': 'Admin'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
