# Generated by Django 5.2 on 2025-05-01 19:08

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-generated_at'], 'verbose_name': 'Report', 'verbose_name_plural': 'Reports'},
        ),
        migrations.AddField(
            model_name='report',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/', verbose_name='Report File'),
        ),
        migrations.AddField(
            model_name='report',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Additional Notes'),
        ),
        migrations.AddField(
            model_name='report',
            name='period_end',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Report Period End'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='period_start',
            field=models.DateField(default=datetime.datetime(2025, 5, 1, 19, 8, 25, 115365, tzinfo=datetime.timezone.utc), verbose_name='Report Period Start'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='admin',
            field=models.ForeignKey(limit_choices_to={'role': 'Admin'}, on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='report',
            name='generated_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Generation Date'),
        ),
        migrations.AlterField(
            model_name='report',
            name='overall_satisfaction_score',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Satisfaction Score (0-5)'),
        ),
        migrations.AlterField(
            model_name='report',
            name='pending_feedback_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Pending Feedback'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('ANNUAL', 'Annual'), ('ADHOC', 'Ad Hoc')], default='WEEKLY', max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='resolved_feedback_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Resolved Feedback'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['report_type'], name='reports_rep_report__dbb097_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['generated_at'], name='reports_rep_generat_35ba4e_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status'], name='reports_rep_status_c732ef_idx'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.CheckConstraint(condition=models.Q(('period_end__gte', models.F('period_start'))), name='period_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.CheckConstraint(condition=models.Q(('overall_satisfaction_score__gte', 0.0), ('overall_satisfaction_score__lte', 5.0)), name='valid_satisfaction_score'),
        ),
    ]
