# Generated by Django 5.2 on 2025-04-24 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='response',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='response',
            old_name='response_text',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='response',
            name='admin',
        ),
        migrations.AddField(
            model_name='feedback',
            name='attachments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='feedback',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='response',
            name='responder',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['Admin', 'Staff']}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='response',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='category',
            field=models.CharField(choices=[('Complaint', 'Complaint'), ('Suggestion', 'Suggestion'), ('Praise', 'Praise')], max_length=50),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='response',
            name='feedback',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='feedback.feedback'),
        ),
    ]
