# Generated by Django 5.2 on 2025-04-28 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_alter_response_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='feedback',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feedback.feedback'),
        ),
    ]
