# Generated by Django 5.2 on 2025-04-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notification_preference',
            field=models.CharField(choices=[('SMS', 'SMS'), ('Email', 'Email'), ('Both', 'Both')], default='Both', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
