# Generated by Django 5.2 on 2025-04-09 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_notification_preference_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Patient', 'Patient'), ('Admin', 'Admin')], default='Patient', max_length=10),
        ),
    ]
