# Generated by Django 5.2 on 2025-04-22 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='preferred_language',
            field=models.CharField(default='en', help_text="User's preferred language (ISO 639-1 code, e.g., 'en', 'sw', 'fr')", max_length=10),
        ),
    ]
