# Generated by Django 5.2 on 2025-05-02 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customuser_options_alter_profile_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='facebook_id',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='google_id',
        ),
        migrations.AddField(
            model_name='profile',
            name='dark_mode',
            field=models.BooleanField(default=False, verbose_name='dark mode'),
        ),
        migrations.AddField(
            model_name='profile',
            name='font_size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=10, verbose_name='font size'),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('sw', 'Swahili'), ('es', 'Spanish'), ('fr', 'French')], default='en', max_length=5, verbose_name='preferred language'),
        ),
    ]
