# Generated by Django 5.2 on 2025-11-29 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_customuser_facebook_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='facebook_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='facebook ID'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='google_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='google ID'),
        ),
    ]
